backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Slideshow Images, name: images, widget: list, field: {label: Image, name: image, widget: image}}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}, {label: Images, name: pics, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Description, name: alt, widget: string}]}]}
          - label: Intro
            name: intro
            widget: object
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Subheading
                name: subheading
                widget: text
              - label: Therapists
                name: blurbs
                widget: list
                fields:
                  - label: Image
                    name: image
                    widget: image
                  - label: Name
                    name: name
                    widget: text
                  - label: Role
                    name: role
                    widget: text
                  - label: Scroll ID
                    name: id
                    widget: text
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - label: Intro
            name: intro
            widget: object
            fields:
              - label: Image
                name: image
                widget: image
              - label: Image Description
                name: imageText
                widget: string
              - label: Body
                name: body
                widget: markdown
          - label: Therapists
            name: therapists
            widget: list
            fields:
              - label: Scroll ID
                name: id
                widget: string
              - label: Image
                name: image
                widget: image
              - label: Name
                name: name
                widget: string
              - label: Phone
                name: phone
                widget: string
              - label: Email
                name: email
                widget: string
              - label: Specialties
                name: specialties
                widget: list
                field: {label: Specialty, name: specialty, widget: string}
              - label: Body
                name: body
                widget: markdown
      - file: "src/pages/services/index.md"
        label: "Services"
        name: "services"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "services-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: Image, name: image, widget: image}
          - {label: "Body", name: "body", widget: "markdown"}
